name: CD - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: qarani/frontend-server:latest
        build-args: |
          SPRING_PROFILES_ACTIVE=prod

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
        script: |
          echo "${{ secrets.FRONTEND_SERVER_PROD_ENV }}" > /home/${{ secrets.EC2_USERNAME }}/.frontend-server-prod.env
          docker pull qarani/frontend-server:latest
          docker stop frontend-server || true
          docker rm frontend-server || true
          docker run -d --name frontend-server --network mini-aws-network --env-file /home/${{ secrets.EC2_USERNAME }}/.frontend-server-prod.env -p 5173:80 qarani/frontend-server:latest




